services:
  aries-vcr-vc-service:
    build:
     context: ..
     dockerfile: docker/Dockerfile
    environment:
      ARIES_VCR_URL: "http://vcr-api:8080"
    ports:
      - "3333:80"
    networks:
      - orgbook

networks:
 orgbook:
  name: vcr_vcr
  external: true