services:
  vcr-vc-service:
    build:
     context: ..
     dockerfile: docker/Dockerfile
    environment:
      ARIES_VCR_URL: ${ARIES_VCR_URL:-http://vcr-api:8080}
    ports:
      - "3333:8080"
    networks:
      - orgbook

networks:
 orgbook:
  name: vcr_vcr
  external: true